version: '3.8'
services:
  mysql:
    image: mysql:8.0
    container_name: mysql-nest-blog
    ports:
      - $DB_PORT:3306
    volumes:
      - mysql-blog:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_NAME}

volumes:
  mysql-blog:
