###Get all post
Get http://localhost:3000/post/all-post
# ?tag=tag1&categoryId=1&&search=concac

### get post by slug
GET http://localhost:3000/post/slug-test-89

### delete post
Delete http://localhost:3000/post/delete/tao-caccac


### get post by user
Get http://localhost:3000/post/user/1